/*
 * generated by Xtext 2.18.0.M3
 */
package org.aut2txs.tool.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class AldebaranLangUiModule extends AbstractAldebaranLangUiModule {
}
