/**
 * generated by Xtext 2.18.0.M3
 */
package org.aut2txs.tool.ide;

import org.aut2txs.tool.ide.AbstractAldebaranLangIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AldebaranLangIdeModule extends AbstractAldebaranLangIdeModule {
}
