/**
 * generated by Xtext 2.18.0.M3
 */
package org.aut2txs.tool.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.aut2txs.tool.AldebaranLangRuntimeModule;
import org.aut2txs.tool.AldebaranLangStandaloneSetup;
import org.aut2txs.tool.ide.AldebaranLangIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AldebaranLangIdeSetup extends AldebaranLangStandaloneSetup {
  @Override
  public Injector createInjector() {
    AldebaranLangRuntimeModule _aldebaranLangRuntimeModule = new AldebaranLangRuntimeModule();
    AldebaranLangIdeModule _aldebaranLangIdeModule = new AldebaranLangIdeModule();
    return Guice.createInjector(Modules2.mixin(_aldebaranLangRuntimeModule, _aldebaranLangIdeModule));
  }
}
