/*
 * generated by Xtext 2.18.0.M3
 */
package org.aut2txs.tool.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class AldebaranLangProposalProvider extends AbstractAldebaranLangProposalProvider {
}
