/*
 * generated by Xtext 2.18.0.M3
 */
package org.aut2txs.tool


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AldebaranLangRuntimeModule extends AbstractAldebaranLangRuntimeModule {
}
